# Generated by Django 4.1.1 on 2022-10-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='junction',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
