# Generated by Django 4.1.1 on 2022-10-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_studentapplication_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('reg_id', models.CharField(max_length=20)),
                ('file', models.FileField(null=True, upload_to='')),
                ('feedbacks', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
