# Generated by Django 4.1.1 on 2022-10-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
