# Generated by Django 4.1.1 on 2022-10-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_fileupload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='app_date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
